In [3]:
import numpy as np
n = np.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [11]:
new_im2 = n.reshape(3,9) # reshape in 2 dimendional array

In [9]:
new_im = n.reshape(3,3,3) # reshape in 3 dimendional array

In [6]:
import cv2

In [7]:
img = cv2.imread('smallgray.png',0)
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [8]:
# transpose
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [13]:
cv2.imwrite('new_image2.png',new_im2)

True

In [15]:
# flat to 1 dimension
for i in img.flat:
    print(i)
img.flat

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
